ARG NODE_VERSION=18
ARG SERVER_PORT=5000

FROM node:$NODE_VERSION-alpine as base

WORKDIR /app

FROM base as builder

COPY package.json package.json
COPY lerna.json lerna.json
COPY packages/ packages/
RUN yarn install && yarn lerna bootstrap && yarn build && cd ./packages/client && yarn build && yarn build:ssr && cd ../../
RUN yarn lerna add ./packages/client --scope=server

FROM builder as production
WORKDIR /app/packages/server
EXPOSE $SERVER_PORT
CMD [ "node", "./dist/index.js" ]
