export enum UserFields {
  FIRST_NAME = 'FIRST_NAME',
  DISPLAY_NAME = 'DISPLAY_NAME',
  SECOND_NAME = 'SECOND_NAME',
  LOGIN = 'LOGIN',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  PASSWORD = 'PASSWORD',
  OLD_PASSWORD = 'OLD_PASSWORD',
  NEW_PASSWORD = 'NEW_PASSWORD',
  REPEAT_PASSWORD = 'REPEAT_PASSWORD',
}
